version: "3.9"
services:
    minio:
        image: minio/minio
        ports:
            - "9000:9000"
        environment:
            MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
            MINIO_SECRET_KEY: $MINIO_SECRET_KEY
        networks: 
            - mlflow
        volumes: 
            - minio_bucket:/data
        command: server --address 0.0.0.0:9000 /data
    postgres_db:
        environment:
            POSTGRES_DB: $POSTGRES_DB
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
        image: postgres
        networks: 
            - mlflow
        ports:
            - "5432:5432"
    mlflow_tracking:
        environment: 
            MLFLOW_S3_ENDPOINT_URL: http://minio:9000
            AWS_ACCESS_KEY_ID: $MINIO_ACCESS_KEY
            AWS_SECRET_ACCESS_KEY: $MINIO_SECRET_KEY
        depends_on: 
            - postgres_db
            - minio
        image: ml-pipes
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        networks: 
            - mlflow
        command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri postgresql+psycopg2://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres_db:5432/$POSTGRES_DB --default-artifact-root s3://mlflow
networks: 
    mlflow:
        name: mlflow
volumes:
    minio_bucket:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $MINIO_ROOT_PATH
