[tool.poetry]
name = "ml-pipes"
version = "0.1.0"
description = ""
authors = ["viniciusmsousa <vinisousa04@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.3"
numpy = "1.19.5"
pycaret = "^2.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
notebook = "^6.3.0"
ipykernel = "^5.5.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
